<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-12-18 at 19:57:12.
 */
use PHPUnit\Framework\TestCase;
use Calculadora;
include_once './Calculadora.php';

class CalculadoraTest extends TestCase {

    /**
     * @covers Calculadora::suma
     * @todo   Implement testSuma().
     */
    
    
    public function testSuma() {
        if (class_exists('Calculadora')){
            $calc = new Calculadora();
            
            $this->assertEquals(
                7,
                $calc->Suma(3, 4)
                );
            
        } else {
            echo 'La clase no existe';
            die;
        }
    }

}
?>
